/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Game {
  'id' : bigint,
  'title' : string,
  'featured' : boolean,
  'thumbnailUrl' : string,
  'playerCount' : bigint,
  'description' : string,
  'iframeUrl' : string,
  'category' : GameCategory,
  'rating' : number,
}
export type GameCategory = { 'action' : null } |
  { 'strategy' : null } |
  { 'puzzle' : null } |
  { 'arcade' : null } |
  { 'sports' : null } |
  { 'retro' : null };
export interface _SERVICE {
  'getAllGames' : ActorMethod<[], Array<Game>>,
  'getFeaturedGames' : ActorMethod<[], Array<Game>>,
  'getGameById' : ActorMethod<[bigint], Game>,
  'getGamesByCategory' : ActorMethod<[GameCategory], Array<Game>>,
  'searchGames' : ActorMethod<[string], Array<Game>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];