/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const GameCategory = IDL.Variant({
  'action' : IDL.Null,
  'strategy' : IDL.Null,
  'puzzle' : IDL.Null,
  'arcade' : IDL.Null,
  'sports' : IDL.Null,
  'retro' : IDL.Null,
});
export const Game = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'featured' : IDL.Bool,
  'thumbnailUrl' : IDL.Text,
  'playerCount' : IDL.Nat,
  'description' : IDL.Text,
  'iframeUrl' : IDL.Text,
  'category' : GameCategory,
  'rating' : IDL.Float64,
});

export const idlService = IDL.Service({
  'getAllGames' : IDL.Func([], [IDL.Vec(Game)], ['query']),
  'getFeaturedGames' : IDL.Func([], [IDL.Vec(Game)], ['query']),
  'getGameById' : IDL.Func([IDL.Nat], [Game], ['query']),
  'getGamesByCategory' : IDL.Func([GameCategory], [IDL.Vec(Game)], ['query']),
  'searchGames' : IDL.Func([IDL.Text], [IDL.Vec(Game)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const GameCategory = IDL.Variant({
    'action' : IDL.Null,
    'strategy' : IDL.Null,
    'puzzle' : IDL.Null,
    'arcade' : IDL.Null,
    'sports' : IDL.Null,
    'retro' : IDL.Null,
  });
  const Game = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'featured' : IDL.Bool,
    'thumbnailUrl' : IDL.Text,
    'playerCount' : IDL.Nat,
    'description' : IDL.Text,
    'iframeUrl' : IDL.Text,
    'category' : GameCategory,
    'rating' : IDL.Float64,
  });
  
  return IDL.Service({
    'getAllGames' : IDL.Func([], [IDL.Vec(Game)], ['query']),
    'getFeaturedGames' : IDL.Func([], [IDL.Vec(Game)], ['query']),
    'getGameById' : IDL.Func([IDL.Nat], [Game], ['query']),
    'getGamesByCategory' : IDL.Func([GameCategory], [IDL.Vec(Game)], ['query']),
    'searchGames' : IDL.Func([IDL.Text], [IDL.Vec(Game)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };