/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Game {
    id: bigint;
    title: string;
    featured: boolean;
    thumbnailUrl: string;
    playerCount: bigint;
    description: string;
    iframeUrl: string;
    category: GameCategory;
    rating: number;
}
export enum GameCategory {
    action = "action",
    strategy = "strategy",
    puzzle = "puzzle",
    arcade = "arcade",
    sports = "sports",
    retro = "retro"
}
export interface backendInterface {
    getAllGames(): Promise<Array<Game>>;
    getFeaturedGames(): Promise<Array<Game>>;
    getGameById(id: bigint): Promise<Game>;
    getGamesByCategory(category: GameCategory): Promise<Array<Game>>;
    searchGames(searchTerm: string): Promise<Array<Game>>;
}
import type { Game as _Game, GameCategory as _GameCategory } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllGames(): Promise<Array<Game>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGames();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGames();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeaturedGames(): Promise<Array<Game>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeaturedGames();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeaturedGames();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGameById(arg0: bigint): Promise<Game> {
        if (this.processError) {
            try {
                const result = await this.actor.getGameById(arg0);
                return from_candid_Game_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGameById(arg0);
            return from_candid_Game_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGamesByCategory(arg0: GameCategory): Promise<Array<Game>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGamesByCategory(to_candid_GameCategory_n6(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGamesByCategory(to_candid_GameCategory_n6(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchGames(arg0: string): Promise<Array<Game>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchGames(arg0);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchGames(arg0);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_GameCategory_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameCategory): GameCategory {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Game_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Game): Game {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    featured: boolean;
    thumbnailUrl: string;
    playerCount: bigint;
    description: string;
    iframeUrl: string;
    category: _GameCategory;
    rating: number;
}): {
    id: bigint;
    title: string;
    featured: boolean;
    thumbnailUrl: string;
    playerCount: bigint;
    description: string;
    iframeUrl: string;
    category: GameCategory;
    rating: number;
} {
    return {
        id: value.id,
        title: value.title,
        featured: value.featured,
        thumbnailUrl: value.thumbnailUrl,
        playerCount: value.playerCount,
        description: value.description,
        iframeUrl: value.iframeUrl,
        category: from_candid_GameCategory_n4(_uploadFile, _downloadFile, value.category),
        rating: value.rating
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    action: null;
} | {
    strategy: null;
} | {
    puzzle: null;
} | {
    arcade: null;
} | {
    sports: null;
} | {
    retro: null;
}): GameCategory {
    return "action" in value ? GameCategory.action : "strategy" in value ? GameCategory.strategy : "puzzle" in value ? GameCategory.puzzle : "arcade" in value ? GameCategory.arcade : "sports" in value ? GameCategory.sports : "retro" in value ? GameCategory.retro : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Game>): Array<Game> {
    return value.map((x)=>from_candid_Game_n2(_uploadFile, _downloadFile, x));
}
function to_candid_GameCategory_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GameCategory): _GameCategory {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GameCategory): {
    action: null;
} | {
    strategy: null;
} | {
    puzzle: null;
} | {
    arcade: null;
} | {
    sports: null;
} | {
    retro: null;
} {
    return value == GameCategory.action ? {
        action: null
    } : value == GameCategory.strategy ? {
        strategy: null
    } : value == GameCategory.puzzle ? {
        puzzle: null
    } : value == GameCategory.arcade ? {
        arcade: null
    } : value == GameCategory.sports ? {
        sports: null
    } : value == GameCategory.retro ? {
        retro: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
